dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - ".github/**/*"
  - "img/**/*"
  - "*.bbx"
  - "*.bst"
  - "*.cbx"
  - "*.dbx"
  - "*.cls"
  - "*.pdf"
  - "*.md"
  - "*.code-workspace"
  - ".typo-ci.yml"

# Any typos we should ignore?
excluded_words:
  - typoci
  - dvipdfmx
  - sigconf
  - sigchi

# Would you like filenames to also be spellchecked?
spellcheck_filenames: true