name: Publish PDF

on:
  push:
    tags: v*.*.*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build docker image
        uses: ./.github/actions/latex
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
